name: course_demo
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=22.3.1=py37h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.7.16=h7a1cb2a_0
  - readline=8.3=hc2a1206_0
  - setuptools=65.6.3=py37h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.38.4=py37h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - altair==5.0.1
      - attrs==24.2.0
      - backports-zoneinfo==0.2.1
      - blinker==1.6.3
      - cachetools==5.5.2
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cycler==0.11.0
      - decorator==5.1.1
      - fonttools==4.38.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - greenlet==3.1.1
      - idna==3.10
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - jinja2==3.1.6
      - jsonschema==4.17.3
      - kiwisolver==1.4.5
      - markdown-it-py==2.2.0
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - mdurl==0.1.2
      - numpy==1.21.6
      - packaging==23.2
      - pandas==1.3.5
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - plotly==5.18.0
      - protobuf==4.24.4
      - pyarrow==12.0.1
      - pydeck==0.8.1b1
      - pygments==2.17.2
      - pympler==1.1
      - pyparsing==3.1.4
      - pyrsistent==0.19.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pytz-deprecation-shim==0.1.0.post0
      - requests==2.31.0
      - rich==13.8.1
      - scipy==1.7.3
      - six==1.17.0
      - smmap==5.0.2
      - sqlalchemy==2.0.46
      - streamlit==1.23.1
      - tenacity==8.2.3
      - toml==0.10.2
      - toolz==0.12.1
      - tornado==6.2
      - typing-extensions==4.7.1
      - tzdata==2025.3
      - tzlocal==4.3.1
      - urllib3==2.0.7
      - validators==0.20.0
      - watchdog==3.0.0
      - zipp==3.15.0
prefix: /home/shaikh/miniconda3/envs/course_demo
